version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - CORS_ALLOWED_ORIGINS=http://localhost:5000,http://localhost:5173,http://frontend:5173
    volumes:
      - ./backend/dashboard.db:/app/dashboard.db
      - ./backend/visibility.json:/app/visibility.json
    restart: unless-stopped
    networks:
      - dashboard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge 